apiVersion: skaffold/v1beta11
kind: Config
build:
  artifacts:
  - image: marketsummary-java
    context: .
deploy:
  helm:
    releases:
      - name: marketsummary-java
        wait: true
        chartPath: ./charts/marketsummary-java
        values:
          image: marketsummary-java
        setValueTemplates:
          istioDomain: "{{.ISTIO_DOMAIN}}"
          productName: "{{.PRODUCT_NAME}}"
        setValues:
          hpa.enabled: true
