{{- if and (not .Values.canary.enabled) (not (eq .Values.istioDomain "")) -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
spec:
  gateways:
  - istio-system/app-gateway
  hosts:
  - marketsummary-java-{{ .Values.productName }}.{{ .Values.istioDomain }}
  http:
  - match:
    - uri:
       prefix: /
    rewrite:
      uri: /marketSummary
    route:
    - destination:
        host: {{ .Chart.Name }}
        port:
          number: 8080
{{- end }}
